#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# git
ln -s ${BASEDIR}/gitconfig ~/.gitconfig

# vim
ln -s ${BASEDIR}/vimrc ~/.vimrc
ln -s ${BASEDIR}/vim/ ~/.vim

# bash
ln -s ${BASEDIR}/bash_profile ~/.bash_profile

# zsh
# ln -s ${BASEDIR}/zshrc ~/.zshrc
