print ' '
print ' dont talk to me or my son ever again'
print '          __                         ' 
print '         /  \                        ' 
print '        / oo \                       ' 
print '        |  _ |                       ' 
print '        | / \|                       ' 
print '         \__/                        ' 
print '        __| |__                      ' 
print '       /       \                     ' 
print '      /         \           __       ' 
print '     /_/|     |\_\         /  \      ' 
print '    / / |     | \ \       / oo \     ' 
print '    \ \ |     | / /       | / \|     ' 
print '     \ \|     |/ /         \__/      ' 
print '      \ |.   .| /         __| |__    ' 
print '       ::_____;:         /       \   ' 
print '        |     |         /_|     |_\  ' 
print '        |  |  |        / /|     |\ \ ' 
print '        |  |  |        \ \|     |/ / ' 
print '        |  |  |         \ |.   .| /  ' 
print '        |  |  |          ::_____;:   ' 
print '        |  |  |           |     |    ' 
print '        |  |  |           |  |  |    ' 
print '        |  |  |           |  |  |    ' 
print '        |  |  |           |  |  |    ' 
print '       /___|___\         /___|___\   ' 
print '                                     '
